[package]
name = "spider"
version = "0.1.0"
authors = ["zhouyelin"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.6.1"
reqwest = "0.9.11"
regex = "1.1.2"
html5ever = "0.22.5"
diesel = { version = "1.3.0", features = ["mysql"] }
dotenv = "0.10"
mysql = "15.1.0"